### ISSUE TITLE
FastAPI tutorial and health check endpoint

### ISSUE THREAD

**Issue by kathmandu777** [MURATA-Laboratory/seminar-2022-backend#2]
# Overview
- FastAPIのチュートリアルを見る
- `/haelth` パスに `GET` をしたら、`{"status": "OK"}` がレスポンスされるエンドポイントを作成する = (health check endpoint)
  - DBはまだいらない (接続してもいいよ かなりむずいと思う)

## Notes📝
- 調べたことをどんどんコメントする
- わからないことがあれば、Slack or GitHubで @kathmandu777 をメンションして質問する
  - 質問力はエンジニアにとって重要なスキル
  - qiitaとかで調べたら、良い質問の仕方が出てきます

**Comment by taito-nakada** [comment]
problem
 pipで入っているはずのuvicornが見つからない。
reason
 シェルがuvicorn実行可能ファイルを見つけられない。
solution
 実行可能ファイルをPATHに追加。

https://atmarkit.itmedia.co.jp/flinux/rensai/linuxtips/035addnewpath.html

**Comment by taito-nakada** [comment]
fastAPIの流れ

インスタンスを定義
↓
パス、オペレーションを設定
↓
関数が動く

/docs,/redocでAPIドキュメントが表示される。

**Comment by taito-nakada** [comment]
done

**Comment by kathmandu777** [comment]
## PRを出す
1. ブランチを切る
2. ここまでのコードをコミット
3. push
4. PRを出す
  - PRにこのissueを紐付ける
  - そうすると、そのPRがマージされた段階で自動的に紐付いているissueがクローズされます
  - これからコード変更系のタスクの場合は、手動でissueを閉じずにPRで閉じるようにしよう
